/hardware_node:
  ros__parameters:
    motor_names:
    #- pan_motor
    #- tilt_motor
    - left_wheel_motor
    - right_wheel_motor
    left_wheel_motor:
      brake_mode: false
      current_lim:
        abs_lim: 80.0
        enable: true
        lim_trigger: 40.0
        time_window: 0.5
      follower: -1
      id: 3
      inverted: false
      pid:
        izone: 0.0
        kd: 0.0
        kf: 0.0
        ki: 0.0
        kp: 0.0
      type: TalonFx
      vcomp: 11.0
    pan_motor:
      brake_mode: false
      current_lim:
        abs_lim: -1.0
        enable: true
        lim_trigger: -1.0
        time_window: -1.0
      follower: -1
      id: 1
      inverted: false
      pid:
        izone: 0.0
        kd: 0.0
        kf: 0.0
        ki: 0.0
        kp: 0.0
      type: TalonFx
      vcomp: -1.0
    right_wheel_motor:
      brake_mode: false
      current_lim:
        abs_lim: 80.0
        enable: true
        lim_trigger: 40.0
        time_window: 0.5
      follower: -1
      id: 0
      inverted: false
      pid:
        izone: 0.0
        kd: 0.0
        kf: 0.0
        ki: 0.0
        kp: 0.0
      type: TalonFx
      vcomp: 11.0
    tilt_motor:
      brake_mode: false
      current_lim:
        abs_lim: -1.0
        enable: true
        lim_trigger: -1.0
        time_window: -1.0
      follower: -1
      id: 2
      inverted: false
      pid:
        izone: 0.0
        kd: 0.0
        kf: 0.0
        ki: 0.0
        kp: 0.0
      type: TalonFx
      vcomp: -1.0
